### PR TITLE
Convert Gulpfile in generated app to use 2 spaces, resolves #14

### LINKED ISSUE #14: Generated app Gulpfile should have tabs with 2 spaces

### PR DESCRIPTION
**Pull request by johnheroy**

### CODE REVIEW

**Comment by jamesanthonyferguson** [comment]
I'm not sure, some people are calling this 'mixed mode' revolutionary.

**Comment by jamesanthonyferguson** [comment]
I hear famous is using it

**Comment by gilhooley** [comment]
#corporatepigs

**Comment by gilhooley** [comment]
#eattherich

**Pull request merged**
